### PR TITLE
Example commit

### PR DESCRIPTION
**Pull request by AaronDDM**
Hi,

Just testing to see if GHA runs without issues if a non-repo owner/user makes a PR.

### CODE REVIEW

**Comment by AaronDDM** [comment]
@bahmutov I am running into issues with the following error:
```
The 'Record Key' is missing. Your CI provider is likely not passing private environment variables to builds from forks.
```

This only happens if a non-org user makes a PR to our public repos. I want to know how exactly we can resolve this.

**Comment by bahmutov** [comment]
The record key is a private sensitive environment variable. You don’t want to make it public and make it available to forked projects. Most CIs by default do not pass environment variables to forked builds

**Comment by AaronDDM** [comment]
> The record key is a private sensitive environment variable. You don’t want to make it public and make it available to forked projects. Most CIs by default do not pass environment variables to forked builds
> […](#)
> Sent from my iPhone
> On Nov 9, 2021, at 14:53, Aaron ***@***.***> wrote: ﻿ @bahmutov I am running into issues with the following error: The 'Record Key' is missing. Your CI provider is likely not passing private environment variables to builds from forks. This only happens if a non-org user makes a PR to our public repos. I want to know how exactly we can resolve this. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

That makes sense - thank you for your quick response.

Essentially the only functionality we would not be able to provide non-org members is the RECORD functionality w/o this key, correct? Everything else should run fine (the actual testing, pass/fail)?

**Comment by bahmutov** [comment]
Exactly. It should still run - and I suggest storing videos and screenshots on CI without recording to the dashboard

**Comment by AaronDDM** [comment]
Amazing, thanks so much @bahmutov - this has been incredibly helpful. 

Will close this.

**Pull request closed without merging**
